### ISSUE TITLE
Reload MathSymbolsInput.plist if it changes

### ISSUE THREAD

**Issue by ryanorendorff** [knrafto/MathSymbolsInput#23]
Hi,

I was attempting to package this input method with a declarative build setup (see https://github.com/LnL7/nix-darwin/pull/587). It works well, but one problem is that if the list of custom commands is updated then the input method does not pick up the changes until the user logs out. The way this setup works is that it generates a `com.mathsymbolsinput.inputmethod.MathSymbolsInput.plist` file and then symlinks that into `/Users/USER/Preferences/`.

This is entirely a synthetic problem of my own making (and so don't expect any changes), but I was curious if it might make sense to add some ability to update the internal command buffer if the preference file changes. Potentially either through some sort of watch method (which may not work with the symlink) or by loading the preferences file each time the input method is switched to.

This may also help solve https://github.com/knrafto/MathSymbolsInput/issues/17. You can see how I am attempting to share configurations between machines [here](https://github.com/LnL7/nix-darwin/pull/587/files#diff-958f4207df90d88e28f43651b5a7be1eb6d260f0ed430f103764eaf6a939c410).

**Comment by knrafto** [comment]
We use [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults) and I don't think there's a way to force-reload from disk. But the built-in `defaults` command can update preferences in a way that will take effect immediately in the input method:

```bash
$ cat /tmp/custom-commands.txt
{
    "\\shrug" = "\U00af\\_(\U30c4)_/\U00af";
}
$ defaults write com.mathsymbolsinput.inputmethod.MathSymbolsInput CustomCommands "$(cat /tmp/custom-commands.txt)"
```

**Comment by ryanorendorff** [comment]
Ah yes that works, thank you! 

I'm still probably doing something gross but I use the plist generated by the nix build to completely replace the plist in the preferences folder using `defaults`. So essentially I run this 

```
defaults write ~/Library/Preferences/com.mathsymbolsinput.inputmethod.MathSymbolsInput.plist \
"$(defaults read ${custom-commands-plist} | sed 's|\\\\|\\|g')"
```

which expands to something like the following.

```
defaults write ~/Library/Preferences/com.mathsymbolsinput.inputmethod.MathSymbolsInput.plist \ 
"$(defaults read /nix/store/x1fb4f4pb9q7g55vz1x760bxsvimz8ql-commands-plist/com.mathsymbolsinput.inputmethod.MathSymbolsInput.plist 
   | sed 's|\\\\|\\|g'
)"
```

and now my updates in my nix darwin file are reflected by the input method!

Thanks again for the help.

**Comment by knrafto** [comment]
You're welcome! Yeah, I wouldn't call that "officially supported" or anything but I'm glad it works.
